// Configuration file

// Wifi
#define IOT_CONFIG_WIFI_SSID "YOUR_WIFI_SSID"
#define IOT_CONFIG_WIFI_PASSWORD "YOUR_WIFI_PASSWORD"

// Azure IoT
#define IOT_CONFIG_IOTHUB_FQDN "YOUR_IOT_HUB_HOST_NAME"
#define IOT_CONFIG_DEVICE_ID "YOUR_DEVICE_ID"
#define IOT_CONFIG_DEVICE_KEY "YOUR_DEVICE_PRIMARY_KEY"

// Publish 1 message every 30 seconds
#define TELEMETRY_FREQUENCY_MILLISECS 30000
